#!/bin/sh
##debug_Aaron on 11/30/2004, killall5 -15 will cause system reboot
##echo "Sending all processes the TERM signal..." 
##/sbin/killall5 -15
##sleep 5 
echo "Sending all processes the KILL signal..."  
/sbin/killall5 -9

sleep 2

echo "Turning off swap..."
swapoff -a

echo "Sync filesystems..."
sync
sync

echo "Unmount all filesystems..."
##Charles on 08/22/2005, change if include LOOP-AES module use loumount
if [ -f "/sbin/loumount" ]; then
	loumount -a -r -f
else
	umount -a -r -f
fi

##echo "Sync filesystems..."
##sync
##sync

sleep 2

/sbin/halt
