#!/bin/sh

ODWATCHDOG_FLAGS=""
ODWATCHDOG=/usr/bin/od-watchdog

case "$1" in
start)
    if [ -x "$ODWATCHDOG" ] ; then
        echo "start od-watchdog"
        rm /tmp/__mounted;
        ${ODWATCHDOG} ${ODWATCHDOG_FLAGS} &
    fi
    ;;

stop)
    echo "stop od-watchdog"
    killall -q od-watchdog
    ;;

restart)
    $0 stop
    $0 start
    ;;

*)
    echo "usage: $0 { start | stop | restart }" >&2
    exit 1
    ;;

esac