#!/bin/sh

HOME=/
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/hddapp/bin:/usr/hddapp/sbin:/usr/local/bin:/usr/local/sbin
export HOME PATH

echo "Mounting proc filesystem..."
mount -n -t proc /proc /proc

uname -r | grep "2.6"
if [ $? = 0 ]; then
	mkdir -p /sys
	mount -n -t sysfs /sys /sys
	mount -t usbfs usbfs /proc/bus/usb 
else
	mount -t usbdevfs usbdevfs /proc/bus/usb
fi

. /etc/rc.conf

echo "Mounting tmpfs to copy file from flash..."
mkdir -p /tmpmnt
uname -r | grep "2.6"
if [ $? = 0 ]; then
	mount -t tmpfs tmpfs /tmpmnt -o size=30m
else
	mount -t tmpfs tmpfs /tmpmnt -o size=20m
fi

ConfList="/etc/rc.conf"
for ThisConfig in $ConfList;
do
	if [ -r "$ThisConfig" ]; then
		. $ThisConfig
	fi
done

if [ -e /etc/powermgmt ]; then
	echo "Enable factory reset"
	chmod +x /etc/powermgmt
	/etc/powermgmt &
fi



if [ $RouterOnly != "Yes" ]; then
	echo HardDiskBootUp=$HardDiskBootUp
	if [ $HardDiskBootUp = "YES" ]; then
        	echo "Boot up from hard disk"
        	if [ -e /etc/rc.RAID.start ]; then
  			sh /etc/rc.RAID.start
        	fi
	else
        	echo "Boot up from flash"
		if [ -e /etc/rc.start ]; then
        		sh /etc/rc.start
		fi
	fi
else
	mkdir /mnt/minix
	mount -t minix /dev/mtdblock5 /mnt/minix
        if [ $? != 0 ]; then
		mkfs.minix /dev/mtdblock5
		mount -t minix /dev/mtdblock5 /mnt/minix
		if [ $? != 0 ]; then
			echo "Mount /dev/mtdblock5 with minix failed!!!"
		else
			echo "Mount /dev/mtdblock5 with minix OK!!!"
		fi	
	else
		echo "Mount /dev/mtdblock5 with minix OK!!!"
	fi
	rm -rf /usr/sausalito/codb
        mkdir /mnt/minix/codb
	cd /usr/sausalito
	ln -s /mnt/minix/codb codb
fi

sh /etc/rc.network_install_version

uname -r | grep "2.6"
if [ $? = 0 ]; then
	if [ -e /lib/modules/r8169.ko ]; then
	      insmod /lib/modules/r8169.ko
	fi
else
	if [ -e /lib/modules/r8169.o ]; then
	      insmod /lib/modules/r8169.o
	fi
fi

if [ ! -d /usr/hddapp/ ]; then
	mkdir -p /usr/hddapp/
	mkdir -p /usr/hddapp/bin
	mkdir -p /usr/hddapp/etc
	mkdir -p /usr/hddapp/sbin
	mkdir -p /usr/hddapp/lib
fi
	
cd /usr/hddapp/sbin;		ln -sf /usr/sbin/smbd sbmd
cd /usr/hddapp/sbin;		ln -sf /usr/sbin/nmbd nmbd
cd /usr/hddapp/bin;			ln -sf /usr/bin/smbpasswd smbpasswd
cd /usr/hddapp/etc;			ln -s /etc/samba samba
cd /usr/hddapp/lib;			ln -s /usr/lib/samba samba
cp /etc/ImageInfo /system

if [ -e /usr/hddapp/lib/samba/libiconv.so.2 ]; then
	ln -s /usr/hddapp/lib/samba/libiconv.so.2  /usr/lib/libiconv.so.2
fi
if [ -e /usr/hddapp/lib/libid3tag.so.0.2.0 ]; then
	ln -s /usr/hddapp/lib/libid3tag.so.0.2.0 /usr/lib/libid3tag.so.0
fi
if [ -e /usr/hddapp/lib/libgdbm.so.3 ]; then
        ln -s /usr/hddapp/lib/libgdbm.so.3 /usr/lib/libgdbm.so.3
fi
if [ -e /usr/etc/mt-daapd.conf ]; then
       ln -s /usr/etc/mt-daapd.conf /etc/mt-daapd.conf
fi 

if [ -e /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavcodec.so.52 ]; then
	ln -s /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavcodec.so.52 /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavcodec.so
fi

if [ -e /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavformat.so.52 ]; then
	ln -s /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavformat.so.52 /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavformat.so
fi

if [ -e /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavutil.so.50 ]; then
	ln -s /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavutil.so.50 /usr/local/share/dlna/mpe_server/ffmpeg_libs/libavutil.so
fi

if [ -e /usr/local/share/dlna/mpe_server/ffmpeg_libs/libswscale.so.0 ]; then
	ln -s /usr/local/share/dlna/mpe_server/ffmpeg_libs/libswscale.so.0 /usr/local/share/dlna/mpe_server/ffmpeg_libs/libswscale.so
fi

echo "Umount tmpfs..."
sleep 2
umount -f /tmpmnt

chmod +x /etc/setconf

/sbin/ifconfig eth0 up
if [ -x /usr/sausalito/sbin/cced ]; then
    if [ ! -e /system/ImageInfo ]; then 
	        rm -rf /usr/sausalito/conf/base/nfs
	        rm -rf /usr/sausalito/conf/base/samba
	        rm -rf /usr/susalito/conf/base/printer
          if [ $NETWORK_INSTALL_VERSION != "YES" ]; then	        
	            rm -rf /usr/sausalito/conf/base/ftp
	            rm -rf /usr/sausalito/constructor/*ftp
	        fi
	        rm -rf /usr/sausalito/conf/base/casgle
          rm -rf /usr/sausalito/constructor/*nfs
          rm -rf /usr/sausalito/constructor/*samba
          rm -rf /usr/sausalito/constructor/*printer
	        rm -rf /usr/sausalito/constructor/*foldershare
	        rm -rf /usr/sausalito/constructor/*casgle
    fi	

    uname -r | grep "2.6"
    if [ $? = 0 ]; then
		  
		  if [ -e /lib/modules/rt5390ap.ko ]; then
            		/sbin/insmod /lib/modules/rt5390ap.ko
		  fi
	      if [ -e /lib/modules/rt2561ap.ko ]; then	
            		/sbin/insmod /lib/modules/rt2561ap.ko
	      fi
	      if [ -e /lib/modules/rt2860ap.ko ]; then
            		/sbin/insmod /lib/modules/rt2860ap.ko
       	      fi
	      if [ -e /lib/modules/rt2880_iNIC.ko ]; then
		        /sbin/insmod /lib/modules/rt2880_iNIC.ko 
	      fi		
    else
	      if [ -e /lib/modules/rt2561ap.o ]; then	
        	  /sbin/insmod /lib/modules/rt2561ap.o
	      fi
    fi
    
    if [ "${UseCodbFlash}" = "YES" ]; then              
        rm -rf /usr/sausalito/codb
        /usr/sausalito/bin/sys_init codb_load
        if [ -e "/usr/sausalito/codb/codb_crc" ]; then
            echo "codb is found"
                /usr/sausalito/sbin/cced -nh
                /usr/sausalito/bin/sys_init codb_renew
                killall cced
		else
			/etc/setconf -factoryreset
        fi                                            
        /usr/sausalito/sbin/cced -codb_flash     
    else                                       
        /usr/sausalito/sbin/cced                 
    fi

    sleep 1
    /usr/sausalito/bin/sys_init > /dev/null 2>&1
    if [ -x /usr/sausalito/bin/hotplug ]; then
        ln -sf /usr/sausalito/bin/hotplug  /sbin/hotplug    
    fi

    MYPATH=/system/local/etc/rc.d
    if [ $? = 0 ]; then
        for i in /system/local/etc/rc.d/*.sh; do
          if [ -e $i ]; then
              sh  $i
          fi
        done                          
    fi
fi

echo "4 4 1 7" > /proc/sys/kernel/printk

echo 0 > /proc/sys/dev/cdrom/lock

/usr/bin/sg_raw /dev/sg0 FF 05 BC 01 00 00 00 00 00 00

mkdir -p /tmp/sbd/watchout_run

echo 1 >/tmp/sbd/watchout_run/dhcpd
chmod +x /etc/restart_dhcpd.sh

mkdir -p /home/public_ftp
ln -s /mnt/ /home/public_ftp/USB_STORAGE
ln -s /mnt/cdrom /home/public_ftp/TSST_ODD

if [ ! -x /usr/sausalito/sbin/cced ]; then

network_system="/etc/sysconfig/network"
HOSTNAME=`grep -s ^HOSTNAME ${network_system} | awk -F = '{print $2}' | sed 's/ //g'`

if [ -z "${HOSTNAME}" ]; then
     HOSTNAME="${hostname:-nas.mydomain.com}"
fi
hostname ${HOSTNAME}
echo -n "Hostname: "
hostname

CWD=`pwd`
cd /etc/sysconfig/network-scripts

network_interfaces=`ls ifcfg* | sed 's/^ifcfg-//g'`

echo -n "Network interfaces: "
for thisif in $network_interfaces;
do
	echo -n "$thisif "
	ThisIfConf="/etc/sysconfig/network-scripts/ifcfg-${thisif}"
	BOOTPROTO=`grep -s ^BOOTPROTO ${ThisIfConf} | awk -F = '{print $2}' | sed 's/ //g'`
	if [ "${BOOTPROTO}" = "none" -o ${thisif} = "lo" ]; then
		IPADDR=`grep -s ^IPADDR ${ThisIfConf} | awk -F = '{print $2}' | sed 's/ //g'`
		NETMASK=`grep -s ^NETMASK ${ThisIfConf} | awk -F = '{print $2}' | sed 's/ //g'`
		thisvalue="inet ${IPADDR} netmask ${NETMASK}"
		eval \ifconfig_${thisif}='$thisvalue'
		GATEWAY=`grep -s ^GATEWAY ${network_system} | awk -F = '{print $2}' | sed 's/ //g'`
	else
       	eval \ifconfig_${thisif}='dhcp'
	fi
done

if [ -n "$GATEWAY" ]; then
	defaultrouter=$GATEWAY
fi

echo 
cd $CWD

for PidDir in /var/run /etc/dhcpc;
do
	rm -rf ${PidDir}/*.pid
done

if [ -r /etc/rc.network -a "${networking}" = "yes" ]; then
	. /etc/rc.network
	start_network
fi


fi

if [ -r "/etc/sysctl.conf" ]; then
	/sbin/sysctl -p /etc/sysctl.conf
fi

case ${ntpdate_enable} in
[Nn][Oo])
    ;;
*)
    echo "Starting ntpdate..."; ${ntpdate_program:-/usr/bin/ntpdate} ${ntpdate_flags}
    ;;
esac

case ${inetd_enable} in
[Nn][Oo])
	;;
*)
	echo "Starting inetd..."; ${inetd_program:-/usr/sbin/inetd} ${inetd_flags}
	;;
esac

case ${crond_enable} in
[Nn][Oo])
	;;
*)
	echo "Starting crond..."; ${crond_program:-/usr/sbin/crond} ${crond_flags}
	;;
esac


#######################################################################################

for device in sda sdb
do
	if [ -e /sys/block/$device ]; then
		echo "Found /sys/block/$device"
## TODO test if fixes boot issues with mounting
##      /usr/sausalito/handlers/base/usb_disk/mtPoint.sh /dev/$device /mnt/usba
	fi
done
echo

if [ `/bin/date +%Y` -lt 2007 ]; then
/bin/date 122110102010
fi
if [  -x /usr/sausalito/sbin/cced ]; then
    /usr/sausalito/bin/constructor
    if [ -x /usr/sausalito/sbin/storudp ]; then
       /usr/sausalito/sbin/storudp
    fi
fi

if [ "${UseCodbFlash}" = "YES" ]; then             
  if [ -x /usr/sausalito/sbin/cced ]; then       
      killall cced                               
      /usr/sausalito/sbin/cced -codb_flash -fw   
  fi                                             
fi

if [ -r /etc/rc.local ]; then
	echo -n 'Starting local daemons:'
	sh /etc/rc.local
	echo '.'
fi


echo -n 'Local package initialization:'

if [ -x /usr/sausalito/sbin/cced ]; then
    if [ -z "${local_startup}" ]; then
	    local_startup="/etc/rc.d /usr/local/etc/rc.d"
    fi
else
    if [ -z "${local_startup}" ]; then
	    local_startup="/etc/rc.d  /usr/hddapp/etc/rc.d /usr/local/etc/rc.d"
    fi
fi

slist=""
for dir in ${local_startup}; do
	if [ -d "${dir}" ]; then
		for script in ${dir}/*.sh; do
			slist="${slist} ${script}"
		done
	fi
done

for script in ${slist}; do
	if [ -x "${script}" ]; then
		${script} start
	elif [ -f "${script}" -o -L "${script}" ]; then
		echo -n " (skipping ${script##*/}, not executable)"
	fi
done

if [ ! -x /usr/sausalito/sbin/cced ]; then
	if [ -x /sbin/upnpdevice ]; then
       		/sbin/upnpdevice &
	fi
	if [ -x /sbin/mDNSResponderPosix ]; then
		/sbin/mDNSResponderPosix -n "Storlink NAS" -t _http._tcp -p 80 -b
	fi

    if [ -x /sbin/mDNSResponderPosix ]; then
            /sbin/mDNSResponderPosix -n "Storlink iTune music box" -t _daap._tcp -p 3689 -b
    fi

	if [ -x /sbin/daapd ]; then
		/sbin/daapd -c /usr/hddapp/etc/daapd.conf &
	fi
fi


case ${dlna_enable} in
[Nn][Oo])
	echo "Stopping dlna..."; /etc/dms_smm.sh stop
	;;
*)
	;;
esac

## TODO test if necessary
/usr/bin/config-handler ntp -z ${NTP_TIME_ZONE}
/usr/bin/config-handler wifi -s ${WIFI_SSID} -a ${WIFI_AUTH_MODE} -p ${WIFI_PASSWD}
/usr/bin/config-handler lan -i ${LAN_IPADDR} -m ${LAN_NETMASK}
## TODO test impact of this
/usr/sausalito/handlers/base/upgrade2/upgrade_aging.sh

echo '.'

echo ''

date

exit 0
